keys:
  - &user_storvik E331E028418C84083868F8C99B6E461A1028E09A
  - &user_storvik_age age1ne0lgy3ma0mjw20k98rlw5k7nx5vgx9myap52jrf2rez3f8g8e4qc9hlgc
  - &user_storvik_macbook_age age1lwsqp53leqr3zmrg0aswdtmynne2uldzuctnhfpxzg9tl20s75gqvfekgk
  - &user_retronix_age age1uep5c7y7p5c7vz6d4nqqhuuvrt29ankedcctdn4x9sudyvpgxghs4lancv
  - &host_live_usb age156y45hq8vhyjn00u5h2czqqwa85luhtqk7u9ztw9a7zwqx27jp6qd0zqw6
  - &host_home_server age1zw49tk9u6kyhtfawj2qrkltgcu9fetz4dmg9dxhe2lnrqfvltq0qydudx8

creation_rules:
  - path_regex: hosts/storvik-nixos-matebook/secrets.ya?ml$
    key_groups:
      - pgp:
          - *user_storvik
        age:
          - *user_storvik_age
          - *user_storvik_macbook_age
  - path_regex: hosts/storvik-live/secrets.ya?ml$
    key_groups:
      - pgp:
          - *user_storvik
        age:
          - *host_live_usb
          - *user_storvik_macbook_age
  - path_regex: hosts/storvik-nixos-wsl/secrets.ya?ml$
    key_groups:
      - age:
          - *user_storvik_age
          - *user_storvik_macbook_age
  - path_regex: hosts/home-server/secrets.ya?ml$
    key_groups:
      - age:
          - *user_storvik_age
          - *user_storvik_macbook_age
          - *host_home_server
  - path_regex: hosts/retronix/secrets.ya?ml$
    key_groups:
      - age:
          - *user_storvik_age
          - *user_storvik_macbook_age
          - *user_retronix_age
