keys:
  - &user_storvik E331E028418C84083868F8C99B6E461A1028E09A
  - &user_storvik_work 1F9E158F9C72BC95FD81269380576D012891404E

creation_rules:
  - path_regex: hosts/storvik-nixos-matebook/secrets.ya?ml$
    key_groups:
      - pgp:
          - *user_storvik
          - *user_storvik_work
#  - path_regex: hosts/name/secrets.ya?ml$
#    key_groups:
#      - pgp:
#          - *user_storvik_matebook
#        age:
#          - *user_storvik_nuc
