name: nix flake check
on: [push, pull_request]
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v26
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: nix flake check
        run: |
          nix flake check --no-build
